image: hwrunner:latest
variables:
    GIT_SSL_NO_VERIFY: "true"
    EXEC: budmm
    HW_DIR: hw3
before_script:
    - make clean all -C ${HW_DIR}
stages:
    - build
    - run
    - test
build:
    stage: build
run:
    stage: run
    script:
        - ${HW_DIR}/bin/${EXEC} -h
test:
    stage: test
    script:
        - ${HW_DIR}/bin/${EXEC}_test -S --verbose=0 --timeout 5
